owncloud/configreport

appinfo/info.xml
=> update info.xml to 10.0

lib/AppInfo/Application.php, lib/ReportDataCollector.php
Fixes https://github.com/owncloud/core/issues/27145 for OC 10.
=> Remove old ocs client for oc 10

lib/ReportDataCollector.php
Referencing https://github.com/owncloud/configreport/issues/13
Reorder report items for better readability.
**New**
basic
config
integrity checker
apps
phpinfo
=> Reorder report items

lib/ReportDataCollector.php
Fixes https://github.com/owncloud/configreport/issues/22
To be backported to stable9.1 and stable9.
=> Add config keys from the appconfig table for core

lib/AppInfo/Application.php, lib/Command/ConfigReport.php, lib/ReportDataCollector.php
Show license key as sensitive in the report.
Fixes #26 
Signed-off-by: Sujith H <sharidasan@owncloud.com>
=> Show license key as sensitive in report

lib/ConfigReportEvent.php, lib/ReportDataCollector.php
This extension point will help other apps
to pass the data to configure app using
the extension point provided.
Signed-off-by: Sujith H <sharidasan@owncloud.com>
=> Create an extension point in the app

lib/AdminPanel.php
Fixes https://github.com/owncloud/configreport/issues/35
=> Move to general settings

lib/AdminPanel.php
backport of https://github.com/owncloud/configreport/pull/36
=> [stable10] move to general settings page

appinfo/info.xml
=> Ready for 10.1

.drone.yml, .gitignore, Makefile, tests/run-unit.sh, tests/unit/Controller/ReportControllerTest.php, tests/unit/Http/ReportResponseTest.php, tests/unit/bootstrap.php, tests/unit/phpunit.xml
sending in #48 and #50 combined
Once merged - will port #65 - but as it has php-cs-fixer changes included it should come separate
=> [Stable10] - bootstrap CI

.drone.yml, .gitignore, Makefile, phpunit.xml, tests/acceptance/.gitignore, tests/acceptance/config/behat.yml, tests/acceptance/features/apiConfigReport/occConfigReportReturnCode.feature, tests/acceptance/features/bootstrap/ConfigReportContext.php, tests/acceptance/features/bootstrap/bootstrap.php
Issue #88 
Backport #83 #78 #75 #74 #73 
This gets the acceptance tests, CI scripts and drone matrix in sync with everything that happened in ``master`` the last few months.
=> [stable10] Standardize CI-related scripts

.drone.yml, tests/unit/ReportDataCollectorTest.php
=> Fix oracle unit test

lib/Command/ConfigReport.php, lib/ReportDataCollector.php, tests/unit/ReportDataCollectorTest.php
Add oc table and details to the report.
Signed-off-by: Sujith H <sharidasan@owncloud.com>
=> [stable10] Backport of Add oc tables and details to report

Makefile, phpcs.xml, tests/acceptance/config/behat.yml, vendor-bin/behat/composer.json, vendor-bin/php_codesniffer/composer.json
and Install and run behat from vendor-bin
Backport #92 #93
=> [stable10] Add php_codesniffer to check acceptance test code style

composer.lock, tests/unit/ReportDataCollectorTest.php
1) Adjust PHPUnit Framework namespace for PHPUnit6 
2) Update bamarni/composer-bin-plugin (v1.3.0)  (while we are here)
=> Php unit 5 to 6

.gitignore, CHANGELOG.md, Makefile, appinfo/info.xml
note: makefile is taken from password_policy, then I enabled the vendor dirs for composer
added changelog
for https://github.com/owncloud/configreport/issues/102
=> Prepare for 0.2.0 release

lib/ReportDataCollector.php, tests/unit/ReportDataCollectorTest.php
Remove personal external storages from the
configreport.
Signed-off-by: Sujith H <sharidasan@owncloud.com>
=> Remove personal external storages from the configreport

.gitignore, CHANGELOG.md, Makefile, appinfo/info.xml, lib/ReportDataCollector.php, tests/unit/ReportDataCollectorTest.php
Closes https://github.com/owncloud/configreport/issues/102
=> Release 0.2.0

tests/unit/ReportDataCollectorTest.php, vendor-bin/behat/composer.json
Part of https://github.com/owncloud/QA/issues/647
=> Implement phpunit v8

.drone.star, composer.json, composer.lock
Part of issue https://github.com/owncloud/core/issues/39134
and https://github.com/owncloud/QA/issues/687
=> Update .drone.star and drop PHP 7.2

sonar-project.properties
=> Drop PHP 7.2 in sonar-project.properties

.drone.star, vendor-bin/phan/composer.json
1) Update to latest .drone.star code
2) Bump PHP phan to major version 5
Part of https://github.com/owncloud/QA/issues/696
=> [tests-only]Update to latest .drone.star code

lib/ReportDataCollector.php
Sanitize system config values.
Issue: https://github.com/owncloud/configreport/issues/167
=> Sanitize system config values

.drone.star
- it is better to use directory references from the dir var, rather than using the hard-coded values in every use case.
-  Applied other starlark changes waiting in activity app
- https://github.com/owncloud/QA/issues/734#issue-1173320353
- CI
=> [full-ci]Use directory references and add some changes pending in activity app

CHANGELOG.md, appinfo/info.xml, sonar-project.properties
=> Merge back release 0.2.2

lib/ReportDataCollector.php
new key: wopi.proxy.key
Fixes: https://github.com/owncloud/wopi/issues/263
=> feat: obscure key wopi.proxy.key

CHANGELOG.md, sonar-project.properties
=> Merge back Release 0.3.0
